### ISSUE TITLE
Smarties?

### ISSUE THREAD

**Issue by mdsumner** [alyssafrazee/RSkittleBrewer#10]
Please consider to add Smarties colour scheme in a future release: http://www.nestle.co.uk/brands/chocolate_and_confectionery/chocolate/smarties

**Comment by alyssafrazee** [comment]
A Smarties scheme has been present for quite a while! Enjoy:

```r
library(RSkittleBrewer)
plotSmarties()
```

![image](https://cloud.githubusercontent.com/assets/2006744/17032236/0e0a153c-4f2d-11e6-8450-302dbda71a4f.png)
